Feature/refactor coordinator
RubenAntunes16/AcademyChallenge pull request #11
Opened 2022-11-10 17:47 UTC by RubenAntunes16

2022-11-11 14:05 UTC, cpradobliss requested changes

2022-11-11 14:05 UTC, cpradobliss commented on AcademyChallengeApp/AcademyChallengeApp/Presentation/Coordinators/AppleReposCoordinator.swift
> +    func back() {
this back can lead to some issues since it releases the controller whenever the view disappears. the `viewDidDisappear` will get called both when the user goes back and when **the user goes forward.**

2022-11-17 11:36 UTC, cpradobliss commented on AcademyChallengeApp/AcademyChallengeApp/Presentation/EmojiScreen/EmojisListViewController.swift
> +    weak var delegateTest: TestDelegate?
Is this still needed?

2022-11-17 11:36 UTC, cpradobliss commented on AcademyChallengeApp/AcademyChallengeApp/Presentation/ViewControllerTest.swift
> +        if isMovingToParent {
✅

2022-11-21 11:43 UTC, cpradobliss approved these changes
Retain Cycle is gone 🥳

2022-11-21 11:46 UTC, RubenAntunes16 commented on AcademyChallengeApp/AcademyChallengeApp/Presentation/Coordinators/AppleReposCoordinator.swift
> +    func back() {
Implemented

2022-11-21 11:48 UTC, RubenAntunes16 commented on AcademyChallengeApp/AcademyChallengeApp/Presentation/EmojiScreen/EmojiView.swift
> +    @objc func tapTest() {
Yes. This was implemented only to test the remove and add to childCoordinators

2022-11-21 11:49 UTC, RubenAntunes16 commented on AcademyChallengeApp/AcademyChallengeApp/Presentation/ViewControllerTest.swift
> +class TestViewController: UIViewController {
I already removed.

2022-11-21 11:50 UTC, RubenAntunes16 commented on AcademyChallengeApp/AcademyChallengeApp/Presentation/Coordinators/MainViewCoordinator.swift
> +protocol MainViewDelegate: AnyObject {
Moved

2022-11-21 11:50 UTC, RubenAntunes16 commented on AcademyChallengeApp/AcademyChallengeApp/Presentation/EmojiScreen/EmojisListViewController.swift
> +    weak var delegateTest: TestDelegate?
I removed Test Delegate

2022-11-21 11:51 UTC, merged